apiVersion: v1
kind: ConfigMap
metadata:
  name: playbook-run
  namespace: playbook
data:
  publish-content.yaml: |-
    - name: Gathering local host
      hosts: internal_web
      become: true
      gather_facts: true
      tasks:
        - name: Retrieve content
          ansible.builtin.get_url:
            url: http://www.google.com
            dest: /config/google.htlm
          # headers:
          #   key1: one
          #   key2: two
